<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0-windows</TargetFramework><EnableWindowsTargeting>true</EnableWindowsTargeting><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
  <ItemGroup><Using Include="Xunit" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SistemaDocente.App.Wpf\SistemaDocente.App.Wpf.csproj" />
    <ProjectReference Include="..\..\src\SistemaDocente.Cli\SistemaDocente.Cli.csproj" />
    <ProjectReference Include="..\..\src\SistemaDocente.Updater\SistemaDocente.Updater.csproj" />
  </ItemGroup>
</Project>