<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaDocente.Application\SistemaDocente.Application.csproj" />
    <ProjectReference Include="..\SistemaDocente.Data\SistemaDocente.Data.csproj" />
    <ProjectReference Include="..\SistemaDocente.Presentation\SistemaDocente.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\*.ttf" />
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
