//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: 4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDocente.App.Wpf.Properties
{
    using System;
    using System.Resources;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // Esta clase fue generada automáticamente por la clase StronglyTypedResourceBuilder
    // mediante una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaDocente.App.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture);
        public static string DetalleProyectoTitle => ResourceManager.GetString("DetalleProyectoTitle", resourceCulture);
        public static string DetalleActividadTitle => ResourceManager.GetString("DetalleActividadTitle", resourceCulture);
        public static string ExpedienteTitle => ResourceManager.GetString("ExpedienteTitle", resourceCulture);
        public static string Guardar => ResourceManager.GetString("Guardar", resourceCulture);
        public static string Cancelar => ResourceManager.GetString("Cancelar", resourceCulture);
        public static string Cerrar => ResourceManager.GetString("Cerrar", resourceCulture);
        public static string Agregar => ResourceManager.GetString("Agregar", resourceCulture);
        public static string Eliminar => ResourceManager.GetString("Eliminar", resourceCulture);
        public static string Buscar => ResourceManager.GetString("Buscar", resourceCulture);
        public static string NombreGrupo => ResourceManager.GetString("NombreGrupo", resourceCulture);
        public static string NombreProyecto => ResourceManager.GetString("NombreProyecto", resourceCulture);
        public static string Descripcion => ResourceManager.GetString("Descripcion", resourceCulture);
        public static string FechaInicio => ResourceManager.GetString("FechaInicio", resourceCulture);
        public static string FechaTermino => ResourceManager.GetString("FechaTermino", resourceCulture);
        public static string Observaciones => ResourceManager.GetString("Observaciones", resourceCulture);
        public static string EmptyStateEstudiantes => ResourceManager.GetString("EmptyStateEstudiantes", resourceCulture);
        public static string EmptyStateActividades => ResourceManager.GetString("EmptyStateActividades", resourceCulture);
        public static string EmptyStateExpediente => ResourceManager.GetString("EmptyStateExpediente", resourceCulture);
        public static string ErrorCampoRequerido => ResourceManager.GetString("ErrorCampoRequerido", resourceCulture);
        public static string ErrorFechaInvalida => ResourceManager.GetString("ErrorFechaInvalida", resourceCulture);
        public static string ErrorRangoFechas => ResourceManager.GetString("ErrorRangoFechas", resourceCulture);
    }
}
